# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='business_choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab_name', models.CharField(default='NULL', max_length=5)),
                ('ex_name', models.CharField(default='expand_name', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='C_S',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='unnamed_S|C', max_length=30)),
                ('public_like', models.PositiveIntegerField(default=0)),
                ('icon', models.ImageField(upload_to='store/icon')),
                ('introduction', models.TextField(default='null', max_length=255)),
                ('index_flag', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('minprice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('maxprice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('detail', models.TextField(blank=True, default='null', max_length=255, null=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('graph_count', models.IntegerField(default=0)),
                ('writed_time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default='BeiJing', max_length=10)),
                ('shop_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed_company', max_length=30)),
                ('icon', models.ImageField(upload_to='store/icon')),
                ('phone', models.CharField(blank=True, default='null', max_length=20, null=True)),
                ('ident', models.BooleanField(default=False)),
                ('isopen', models.BooleanField(default=False)),
                ('inward_phone', models.CharField(max_length=20)),
                ('charge_time', models.DateField(auto_now=True)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.City')),
                ('business_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.business_choices')),
            ],
        ),
        migrations.CreateModel(
            name='flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_name', models.CharField(default='null', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(default=1)),
                ('img', models.ImageField(upload_to='store/img')),
                ('flag', models.CharField(default='', max_length=20)),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.C_S')),
            ],
        ),
        migrations.CreateModel(
            name='ident_Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_name', models.CharField(max_length=20)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('4', '执行中'), ('11', '退款中'), ('25', '其他'), ('12', '已取消'), ('10', '请求退款'), ('5', '结算中'), ('3', '安排中'), ('2', '商议中'), ('99', '已完成'), ('1', '已提交')], default='1', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='server_choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_name', models.CharField(default='NULL', max_length=5)),
                ('ex_ser_name', models.CharField(default="expand_server'name", max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.FileField(blank=True, default='images/matt.jpg', null=True, upload_to='store/userimg')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sex', models.BooleanField(default=1)),
                ('phone', models.CharField(default='', max_length=11)),
                ('ident', models.CharField(max_length=18)),
                ('is_C_man', models.BooleanField(default=False)),
                ('is_W_man', models.BooleanField(default=False)),
                ('belong_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ident_kind', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Web.ident_Kind')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.City')),
            ],
        ),
        migrations.AddField(
            model_name='order_list',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.UserProfile'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='needlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.C_S'),
        ),
        migrations.AddField(
            model_name='company',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.UserProfile'),
        ),
        migrations.AddField(
            model_name='c_s',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.Company'),
        ),
        migrations.AddField(
            model_name='c_s',
            name='service_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.server_choices'),
        ),
    ]
