# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_auto_20180531_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='status',
            field=models.CharField(choices=[('5', '结算中'), ('99', '已完成'), ('4', '执行中'), ('11', '退款中'), ('10', '请求退款'), ('3', '安排中'), ('2', '商议中'), ('12', '已取消'), ('1', '已提交'), ('25', '其他')], default='1', max_length=10),
        ),
    ]
