# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-18 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20180531_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_ser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.C_S')),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_level', models.IntegerField()),
                ('status_name', models.CharField(max_length=10)),
                ('next_1', models.IntegerField(blank=True, null=True)),
                ('next_2', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ident_name',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='status',
            field=models.CharField(choices=[('4', '执行中'), ('11', '退款中'), ('5', '结算中'), ('12', '已取消'), ('1', '已提交'), ('2', '商议中'), ('25', '其他'), ('3', '安排中'), ('99', '已完成'), ('10', '请求退款')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ident',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web.City'),
        ),
        migrations.AddField(
            model_name='fav',
            name='fav_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.UserProfile'),
        ),
    ]
