# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0007_auto_20180618_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Web.status'),
        ),
    ]
