# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0009_auto_20180703_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='introduction',
            field=models.TextField(default='null', max_length=255),
        ),
    ]
