# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-05 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0011_auto_20180704_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('man', 'man'), ('woman', 'woman')], default='man', max_length=5),
        ),
    ]
